require("aman.core.options")
require("aman.core.keymaps")
require("aman.core.colorscheme")
require("aman.plugins-setup")
pcall(require, "aman.plugins.neo-tree")
pcall(require, "aman.plugins.telescope")
pcall(require, "aman.plugins.lsp")
pcall(require, "aman.plugins.treesitter")
pcall(require, "aman.plugins.lualine")
pcall(require, "aman.plugins.gitsigns")
pcall(require, "aman.plugins.indent-blankline")
pcall(require, "aman.plugins.which-key")
pcall(require, "aman.plugins.toggleterm")
pcall(require, "aman.plugins.conform")
pcall(require, "aman.plugins.dadbod")

